routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\CampusController;
use App\Http\Controllers\CulinaryController;
use App\Http\Controllers\DormController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SummaryController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TransportController;
use App\Http\Controllers\WritingController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
Route::group([], function () {
    Route::resource('books', BookController::class);
    Route::resource('campuses', CampusController::class);
    Route::resource('organizations', OrganizationController::class);
    Route::resource('transports', TransportController::class);
    Route::resource('culinaries', CulinaryController::class);
    Route::resource('dorms', DormController::class);
    Route::resource('news', NewsController::class);
    Route::get('news/publish/{id}', [NewsController::class, 'publish'])->name('news.publish');
    Route::get('news/unpublish/{id}', [NewsController::class, 'unpublish'])->name('news.unpublish');

    Route::resource('summaries', SummaryController::class);
    // summary publish and unpublish
    Route::get('summaries/publish/{id}', [SummaryController::class, 'publish'])->name('summaries.publish');
    Route::get('summaries/unpublish/{id}', [SummaryController::class, 'unpublish'])->name('summaries.unpublish');

    Route::resource('writings', WritingController::class);
    // writings publish and unpublish
    Route::get('writings/publish/{id}', [WritingController::class, 'publish'])->name('writings.publish');
    Route::get('writings/unpublish/{id}', [WritingController::class, 'unpublish'])->name('writings.unpublish');

    Route::resource('students', StudentController::class);
    Route::resource('teachers', TeacherController::class);

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');


    // Dashboard
    Route::get('/dashboard-ecommerce-dashboard', function () {
        return view('pages.dashboard-ecommerce-dashboard', ['type_menu' => 'dashboard']);
    });


    // Layout
    Route::get('/layout-default-layout', function () {
        return view('pages.layout-default-layout', ['type_menu' => 'layout']);
    });

    // Blank Page
    Route::get('/blank-page', function () {
        return view('pages.blank-page', ['type_menu' => '']);
    });

    // Bootstrap
    Route::get('/bootstrap-alert', function () {
        return view('pages.bootstrap-alert', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-badge', function () {
        return view('pages.bootstrap-badge', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-breadcrumb', function () {
        return view('pages.bootstrap-breadcrumb', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-buttons', function () {
        return view('pages.bootstrap-buttons', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-card', function () {
        return view('pages.bootstrap-card', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-carousel', function () {
        return view('pages.bootstrap-carousel', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-collapse', function () {
        return view('pages.bootstrap-collapse', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-dropdown', function () {
        return view('pages.bootstrap-dropdown', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-form', function () {
        return view('pages.bootstrap-form', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-list-group', function () {
        return view('pages.bootstrap-list-group', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-media-object', function () {
        return view('pages.bootstrap-media-object', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-modal', function () {
        return view('pages.bootstrap-modal', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-nav', function () {
        return view('pages.bootstrap-nav', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-navbar', function () {
        return view('pages.bootstrap-navbar', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-pagination', function () {
        return view('pages.bootstrap-pagination', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-popover', function () {
        return view('pages.bootstrap-popover', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-progress', function () {
        return view('pages.bootstrap-progress', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-table', function () {
        return view('pages.bootstrap-table', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-tooltip', function () {
        return view('pages.bootstrap-tooltip', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-typography', function () {
        return view('pages.bootstrap-typography', ['type_menu' => 'bootstrap']);
    });


    // components
    Route::get('/components-article', function () {
        return view('pages.components-article', ['type_menu' => 'components']);
    });
    Route::get('/components-avatar', function () {
        return view('pages.components-avatar', ['type_menu' => 'components']);
    });
    Route::get('/components-chat-box', function () {
        return view('pages.components-chat-box', ['type_menu' => 'components']);
    });
    Route::get('/components-empty-state', function () {
        return view('pages.components-empty-state', ['type_menu' => 'components']);
    });
    Route::get('/components-gallery', function () {
        return view('pages.components-gallery', ['type_menu' => 'components']);
    });
    Route::get('/components-hero', function () {
        return view('pages.components-hero', ['type_menu' => 'components']);
    });
    Route::get('/components-multiple-upload', function () {
        return view('pages.components-multiple-upload', ['type_menu' => 'components']);
    });
    Route::get('/components-pricing', function () {
        return view('pages.components-pricing', ['type_menu' => 'components']);
    });
    Route::get('/components-statistic', function () {
        return view('pages.components-statistic', ['type_menu' => 'components']);
    });
    Route::get('/components-tab', function () {
        return view('pages.components-tab', ['type_menu' => 'components']);
    });
    Route::get('/components-table', function () {
        return view('pages.components-table', ['type_menu' => 'components']);
    });
    Route::get('/components-user', function () {
        return view('pages.components-user', ['type_menu' => 'components']);
    });
    Route::get('/components-wizard', function () {
        return view('pages.components-wizard', ['type_menu' => 'components']);
    });

    // forms
    Route::get('/forms-advanced-form', function () {
        return view('pages.forms-advanced-form', ['type_menu' => 'forms']);
    });
    Route::get('/forms-editor', function () {
        return view('pages.forms-editor', ['type_menu' => 'forms']);
    });
    Route::get('/forms-validation', function () {
        return view('pages.forms-validation', ['type_menu' => 'forms']);
    });

    // google maps
    // belum tersedia

    // modules
    Route::get('/modules-calendar', function () {
        return view('pages.modules-calendar', ['type_menu' => 'modules']);
    });
    Route::get('/modules-chartjs', function () {
        return view('pages.modules-chartjs', ['type_menu' => 'modules']);
    });
    Route::get('/modules-datatables', function () {
        return view('pages.modules-datatables', ['type_menu' => 'modules']);
    });
    Route::get('/modules-flag', function () {
        return view('pages.modules-flag', ['type_menu' => 'modules']);
    });
    Route::get('/modules-font-awesome', function () {
        return view('pages.modules-font-awesome', ['type_menu' => 'modules']);
    });
    Route::get('/modules-ion-icons', function () {
        return view('pages.modules-ion-icons', ['type_menu' => 'modules']);
    });
    Route::get('/modules-owl-carousel', function () {
        return view('pages.modules-owl-carousel', ['type_menu' => 'modules']);
    });
    Route::get('/modules-sparkline', function () {
        return view('pages.modules-sparkline', ['type_menu' => 'modules']);
    });
    Route::get('/modules-sweet-alert', function () {
        return view('pages.modules-sweet-alert', ['type_menu' => 'modules']);
    });
    Route::get('/modules-toastr', function () {
        return view('pages.modules-toastr', ['type_menu' => 'modules']);
    });
    Route::get('/modules-vector-map', function () {
        return view('pages.modules-vector-map', ['type_menu' => 'modules']);
    });
    Route::get('/modules-weather-icon', function () {
        return view('pages.modules-weather-icon', ['type_menu' => 'modules']);
    });

    // auth
    Route::get('/auth-forgot-password', function () {

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'author',
        'publisher',
        'year',
        'isbn',
        'cover',
        'file',
        'description',
    ];

    public function summaries()
    {
        return $this->hasMany(Summary::class);
    }

}

app/Http/Controllers/API/V1/BookController.php
<?php

namespace App\Http\Controllers\API\V1;

use App\Models\Book;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class BookController extends Controller
{
    public function index($student_id = null)
    {
        $books = Book::latest()->get();

        $books->map(function ($book) use ($student_id) {
            $book->cover = env('APP_URL') . Storage::url('books/' . $book->cover);
            $book->file = env('APP_URL') . Storage::url('books/' . $book->file);
            $book->is_read = $book->summaries()->where('student_id', $student_id)->exists();
            return $book;
        });

        return response()->json([
            'success' => true,
            'message' => 'List Data Buku',
            'data'    => $books
        ], 200);
    }

    public function show($id)
    {
        $book = Book::find($id);
        $book->cover = env('APP_URL') . Storage::url('books/' . $book->cover);
        $book->file = env('APP_URL') . Storage::url('books/' . $book->file);

        if (!$book) {
            return response()->json([
                'success' => false,
                'message' => 'Buku tidak ditemukan',
                'data'    => null
            ], 404);
        }

        return response()->json([
            'success' => true,
            'message' => 'Detail Data Buku',
            'data'    => $book
        ], 200);
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required|max:255',
            'author' => 'required|max:255',
            'publisher' => 'required|max:255',
            'year' => 'required|integer|min:1900|max:' . (date('Y') + 1),
            'isbn' => 'required|unique:books|max:255',
            'cover' => 'image|mimes:jpeg,png,jpg,gif|max:2048',
            'file' => 'mimes:pdf|max:2048',
            'description' => 'required',
        ]);

        $book = new Book();

        $book->fill($validatedData);

        if ($request->hasFile('cover')) {
            $cover = $request->file('cover');
            $filename = time() . '.' . $cover->getClientOriginalExtension();
            Storage::putFileAs('public/books/covers', $cover, $filename);
            $book->cover = 'covers/' . $filename;
        }

        if ($request->hasFile('file')) {
            $file = $request->file('file');
            $filename = time() . '.' . $file->getClientOriginalExtension();
            Storage::putFileAs('public/books/files', $file, $filename);
            $book->file = 'files/' . $filename;
        }

        $book->save();

        return response()->json([
            'success' => true,
            'message' => 'Buku berhasil ditambahkan',
            'data'    => $book
        ], 200);
    }

    public function update(Request $request, $id)
    {
        $book = Book::find($id);

        if (!$book) {
            return response()->json([
                'success' => false,
                'message' => 'Buku tidak ditemukan',
                'data'    => null
            ], 404);
        }

        $validatedData = $request->validate([
            'title' => 'required|max:255',
            'author' => 'required|max:255',
            'publisher' => 'required|max:255',
            'year' => 'required|integer|min:1900|max:' . (date('Y') + 1),
            'isbn' => 'required|unique:books|max:255',
            'cover' => 'image|mimes:jpeg,png,jpg,gif|max:2048',
            'file' => 'mimes:pdf|max:2048',
            'description' => 'required',
        ]);

        $book->fill($validatedData);

        if ($request->hasFile('cover')) {
            $cover = $request->file('cover');
            $filename = time() . '.' . $cover->getClientOriginalExtension();
            Storage::putFileAs('public/books/covers', $cover, $filename);
            $book->cover = 'covers/' . $filename;
        }

        if ($request->hasFile('file')) {
            $file = $request->file('file');
            $filename = time() . '.' . $file->getClientOriginalExtension();
            Storage::putFileAs('public/books/files', $file, $filename);
            $book->file = 'files/' . $filename;
        }

        $book->save();

        return response()->json([
            'success' => true,
            'message' => 'Buku berhasil diupdate',
            'data'    => $book
        ], 200);
    }

    public function destroy($id)
    {
        $book = Book::find($id);

        if (!$book) {
            return response()->json([
                'success' => false,
                'message' => 'Buku tidak ditemukan',
                'data'    => null
            ], 404);
        }

        $book->delete();

        return response()->json([
            'success' => true,
            'message' => 'Buku berhasil dihapus',
            'data'    => $book
        ], 200);
    }
}

resources/views/books/create.blade.php
@extends('layouts.app')

@section('title', 'Create Book')

@push('style')
    <!-- CSS Libraries -->
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Book</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Book</a></div>
                    <div class="breadcrumb-item"><a href="#">Create</a></div>
                </div>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="card">
                            <form action="{{ route('books.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="card-header">
                                    <h4>Create Book</h4>
                                </div>
                                <div class="card-body row">
                                    <div class="col-md-6 col-lg-6">
                                        {{-- form title --}}
                                        <div class="form-group">
                                            <label>Title</label>
                                            <input type="text" class="form-control @error('title') is-invalid @enderror "
                                                name="title" value="{{ old('title') }}" required="">
                                            @error('title')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form publisher --}}
                                        <div class="form-group">
                                            <label>Publisher</label>
                                            <input type="text"
                                                class="form-control @error('publisher') is-invalid @enderror "
                                                name="publisher" value="{{ old('publisher') }}" required="">
                                            @error('publisher')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form author --}}
                                        <div class="form-group">
                                            <label>Author</label>
                                            <input type="text"
                                                class="form-control @error('author') is-invalid @enderror " name="author"
                                                value="{{ old('author') }}" required="">
                                            @error('author')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form year --}}
                                        <div class="form-group">
                                            <label>Year</label>
                                            <input type="text" class="form-control @error('year') is-invalid @enderror "
                                                name="year" value="{{ old('year') }}" required="">
                                            @error('year')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-lg-6">

                                        {{-- form isbn --}}
                                        <div class="form-group">
                                            <label>ISBN</label>
                                            <input type="text" class="form-control @error('isbn') is-invalid @enderror "
                                                name="isbn" value="{{ old('isbn') }}" required="">
                                            @error('isbn')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form cover file --}}
                                        <div class="form-group">
                                            <label>Cover</label>
                                            <input type="file" class="form-control @error('cover') is-invalid @enderror "
                                                name="cover" value="@old('cover'))">
                                            @error('cover')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form file --}}
                                        <div class="form-group">
                                            <label>File</label>
                                            <input type="file" class="form-control @error('file') is-invalid @enderror "
                                                name="file" value="@old('file'))">
                                            @error('file')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form description --}}
                                        <div class="form-group">
                                            <label>Descriptsion</label>
                                            <textarea class="form-control @error('description') is-invalid @enderror" placeholder="" name="description"
                                                required="" style="height: 100px;">{{ old('description') }}</textarea>
                                            @error('description')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer text-right">
                                    <button class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->

    <!-- Page Specific JS File -->
@endpush

resources/views/books/index.blade.php
@extends('layouts.app')

@section('title', 'Create Book')

@push('style')
    <!-- CSS Libraries -->
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Book</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Book</a></div>
                    <div class="breadcrumb-item"><a href="#">Create</a></div>
                </div>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Tabel Book</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table-bordered table-md table">
                                        <tr>
                                            <th>#</th>
                                            <th>Title</th>
                                            <th>Author</th>
                                            <th>Publisher</th>
                                            <th>Year</th>
                                            <th>ISBN</th>
                                            <th>Cover</th>
                                            <th>File</th>
                                            <th>Description</th>
                                            <th class="text-center">Action</th>
                                        </tr>

                                        @if ($books->isEmpty())
                                            <tr>
                                                <td colspan="8" class="text-center">No data available</td>
                                            </tr>
                                        @endif
                                        @foreach ($books as $book)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $book->title }}</td>
                                                <td>{{ $book->author }}</td>
                                                <td>{{ $book->publisher }}</td>
                                                <td>{{ $book->year }}</td>
                                                <td>{{ $book->isbn }}</td>
                                                <td><img width="100" height="100"
                                                        src="{{ asset("storage/books/$book->cover") }}" alt="">
                                                </td>
                                                <td><a href="{{ asset("storage/books/$book->file") }}" class="text-primary"
                                                        target="_blank">Download</a></td>
                                                <td>{{ $book->description }}</td>
                                                <td>
                                                    <a href="{{ route('books.edit', ['book' => $book]) }}"
                                                        class="btn btn-warning btn-sm">Edit</a>
                                                    <form action="{{ route('books.destroy', $book->id) }}" method="POST"
                                                        class="d-inline">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer text-right">
                                <nav class="d-inline-block">
                                    <ul class="pagination mb-0">
                                        <li class="page-item disabled">
                                            <a class="page-link" href="#" tabindex="-1"><i
                                                    class="fas fa-chevron-left"></i></a>
                                        </li>
                                        <li class="page-item active"><a class="page-link" href="#">1 <span
                                                    class="sr-only">(current)</span></a></li>
                                        <li class="page-item">
                                            <a class="page-link" href="#">2</a>
                                        </li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item">
                                            <a class="page-link" href="#"><i class="fas fa-chevron-right"></i></a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->

    <!-- Page Specific JS File -->
@endpush