routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\CampusController;
use App\Http\Controllers\CulinaryController;
use App\Http\Controllers\DormController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SummaryController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TransportController;
use App\Http\Controllers\WritingController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
Route::group([], function () {
    Route::resource('books', BookController::class);
    Route::resource('campuses', CampusController::class);
    Route::resource('organizations', OrganizationController::class);
    Route::resource('transports', TransportController::class);
    Route::resource('culinaries', CulinaryController::class);
    Route::resource('dorms', DormController::class);
    Route::resource('news', NewsController::class);
    Route::get('news/publish/{id}', [NewsController::class, 'publish'])->name('news.publish');
    Route::get('news/unpublish/{id}', [NewsController::class, 'unpublish'])->name('news.unpublish');

    Route::resource('summaries', SummaryController::class);
    // summary publish and unpublish
    Route::get('summaries/publish/{id}', [SummaryController::class, 'publish'])->name('summaries.publish');
    Route::get('summaries/unpublish/{id}', [SummaryController::class, 'unpublish'])->name('summaries.unpublish');

    Route::resource('writings', WritingController::class);
    // writings publish and unpublish
    Route::get('writings/publish/{id}', [WritingController::class, 'publish'])->name('writings.publish');
    Route::get('writings/unpublish/{id}', [WritingController::class, 'unpublish'])->name('writings.unpublish');

    Route::resource('students', StudentController::class);
    Route::resource('teachers', TeacherController::class);

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');


    // Dashboard
    Route::get('/dashboard-ecommerce-dashboard', function () {
        return view('pages.dashboard-ecommerce-dashboard', ['type_menu' => 'dashboard']);
    });


    // Layout
    Route::get('/layout-default-layout', function () {
        return view('pages.layout-default-layout', ['type_menu' => 'layout']);
    });

    // Blank Page
    Route::get('/blank-page', function () {
        return view('pages.blank-page', ['type_menu' => '']);
    });

    // Bootstrap
    Route::get('/bootstrap-alert', function () {
        return view('pages.bootstrap-alert', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-badge', function () {
        return view('pages.bootstrap-badge', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-breadcrumb', function () {
        return view('pages.bootstrap-breadcrumb', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-buttons', function () {
        return view('pages.bootstrap-buttons', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-card', function () {
        return view('pages.bootstrap-card', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-carousel', function () {
        return view('pages.bootstrap-carousel', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-collapse', function () {
        return view('pages.bootstrap-collapse', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-dropdown', function () {
        return view('pages.bootstrap-dropdown', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-form', function () {
        return view('pages.bootstrap-form', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-list-group', function () {
        return view('pages.bootstrap-list-group', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-media-object', function () {
        return view('pages.bootstrap-media-object', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-modal', function () {
        return view('pages.bootstrap-modal', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-nav', function () {
        return view('pages.bootstrap-nav', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-navbar', function () {
        return view('pages.bootstrap-navbar', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-pagination', function () {
        return view('pages.bootstrap-pagination', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-popover', function () {
        return view('pages.bootstrap-popover', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-progress', function () {
        return view('pages.bootstrap-progress', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-table', function () {
        return view('pages.bootstrap-table', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-tooltip', function () {
        return view('pages.bootstrap-tooltip', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-typography', function () {
        return view('pages.bootstrap-typography', ['type_menu' => 'bootstrap']);
    });


    // components
    Route::get('/components-article', function () {
        return view('pages.components-article', ['type_menu' => 'components']);
    });
    Route::get('/components-avatar', function () {
        return view('pages.components-avatar', ['type_menu' => 'components']);
    });
    Route::get('/components-chat-box', function () {
        return view('pages.components-chat-box', ['type_menu' => 'components']);
    });
    Route::get('/components-empty-state', function () {
        return view('pages.components-empty-state', ['type_menu' => 'components']);
    });
    Route::get('/components-gallery', function () {
        return view('pages.components-gallery', ['type_menu' => 'components']);
    });
    Route::get('/components-hero', function () {
        return view('pages.components-hero', ['type_menu' => 'components']);
    });
    Route::get('/components-multiple-upload', function () {
        return view('pages.components-multiple-upload', ['type_menu' => 'components']);
    });
    Route::get('/components-pricing', function () {
        return view('pages.components-pricing', ['type_menu' => 'components']);
    });
    Route::get('/components-statistic', function () {
        return view('pages.components-statistic', ['type_menu' => 'components']);
    });
    Route::get('/components-tab', function () {
        return view('pages.components-tab', ['type_menu' => 'components']);
    });
    Route::get('/components-table', function () {
        return view('pages.components-table', ['type_menu' => 'components']);
    });
    Route::get('/components-user', function () {
        return view('pages.components-user', ['type_menu' => 'components']);
    });
    Route::get('/components-wizard', function () {
        return view('pages.components-wizard', ['type_menu' => 'components']);
    });

    // forms
    Route::get('/forms-advanced-form', function () {
        return view('pages.forms-advanced-form', ['type_menu' => 'forms']);
    });
    Route::get('/forms-editor', function () {
        return view('pages.forms-editor', ['type_menu' => 'forms']);
    });
    Route::get('/forms-validation', function () {
        return view('pages.forms-validation', ['type_menu' => 'forms']);
    });

    // google maps
    // belum tersedia

    // modules
    Route::get('/modules-calendar', function () {
        return view('pages.modules-calendar', ['type_menu' => 'modules']);
    });
    Route::get('/modules-chartjs', function () {
        return view('pages.modules-chartjs', ['type_menu' => 'modules']);
    });
    Route::get('/modules-datatables', function () {
        return view('pages.modules-datatables', ['type_menu' => 'modules']);
    });
    Route::get('/modules-flag', function () {
        return view('pages.modules-flag', ['type_menu' => 'modules']);
    });
    Route::get('/modules-font-awesome', function () {
        return view('pages.modules-font-awesome', ['type_menu' => 'modules']);
    });
    Route::get('/modules-ion-icons', function () {
        return view('pages.modules-ion-icons', ['type_menu' => 'modules']);
    });
    Route::get('/modules-owl-carousel', function () {
        return view('pages.modules-owl-carousel', ['type_menu' => 'modules']);
    });
    Route::get('/modules-sparkline', function () {
        return view('pages.modules-sparkline', ['type_menu' => 'modules']);
    });
    Route::get('/modules-sweet-alert', function () {
        return view('pages.modules-sweet-alert', ['type_menu' => 'modules']);
    });
    Route::get('/modules-toastr', function () {
        return view('pages.modules-toastr', ['type_menu' => 'modules']);
    });
    Route::get('/modules-vector-map', function () {
        return view('pages.modules-vector-map', ['type_menu' => 'modules']);
    });
    Route::get('/modules-weather-icon', function () {
        return view('pages.modules-weather-icon', ['type_menu' => 'modules']);
    });

    // auth
    Route::get('/auth-forgot-password', function () {

app/Models/Transport.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Transport extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'description',
        'address',
        'price',
        'time',
        'capacity',
        'city',
        'photo',
        'owner',
        'type',
        'number_phone'
    ];
}

app/Http/Controllers/API/V1/TransportController.php
<?php

namespace App\Http\Controllers\API\V1;

use App\Http\Controllers\Controller;
use App\Models\Transport;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class TransportController extends Controller
{
    public function index()
    {
        $transports = Transport::latest()->get();
        $transports->map(function ($transport) {
            $transport->photo = env('APP_URL') . Storage::url('transports/' . $transport->photo);
            return $transport;
        });
        return response()->json([
            'success' => true,
            'message' => 'List Data Transport',
            'data'    => $transports
        ], 200);
    }

    public function show($id)
    {
        $transport = Transport::find($id);

        $transport->photo = env('APP_URL') . Storage::url('transports/' . $transport->photo);

        if (!$transport) {
            return response()->json([
                'success' => false,
                'message' => 'Transport tidak ditemukan',
                'data'    => null
            ], 404);
        }

        return response()->json([
            'success' => true,
            'message' => 'Detail Data Transport',
            'data'    => $transport
        ], 200);
    }

    public function store(Request $request)
    {
        $validateData = $request->validate([
            'name' => 'required|max:255',
            'address' => 'required|max:255',
            'price' => 'required|max:255',
            'rating' => 'required|max:255',
            'is_recommended' => 'required|max:255|default:0',
            'photo' => 'file|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'type' => 'required|max:255',
            'number_phone' => 'required|max:255',
        ]);

        $transport = new Transport();

        $transport->fill($validateData);

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $filename = time() . '.' . $photo->getClientOriginalExtension();
            Storage::putFileAs('public/transports', $photo, $filename);
            $transport->photo = $filename;
        }

        $transport->save();

        return response()->json([
            'success' => true,
            'message' => 'Data Transport berhasil disimpan',
            'data'    => $transport
        ], 200);
    }

    public function update(Request $request, $id)
    {
        $transport = Transport::find($id);

        if (!$transport) {
            return response()->json([
                'success' => false,
                'message' => 'Data Transport dengan id ' . $id . ' tidak ditemukan',
                'data'    => null
            ], 404);
        }

        $validateData = $request->validate([
            'name' => 'required|max:255',
            'address' => 'required|max:255',
            'price' => 'required|max:255',
            'rating' => 'required|max:255',
            'is_recommended' => 'required|max:255|default:0',
            'photo' => 'file|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'type' => 'required|max:255',
            'number_phone' => 'required|max:255',
        ]);

        $transport->fill($validateData);

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $filename = time() . '.' . $photo->getClientOriginalExtension();
            Storage::putFileAs('public/transports', $photo, $filename);
            Storage::delete('public/transports/' . $transport->photo);
            $transport->photo = $filename;
        }

        $transport->save();

        return response()->json([
            'success' => true,
            'message' => 'Data Transport berhasil diupdate',
            'data'    => $transport
        ], 200);
    }

    public function destroy($id)
    {
        $transport = Transport::find($id);

        if (!$transport) {
            return response()->json([
                'success' => false,
                'message' => 'Data Transport dengan id ' . $id . ' tidak ditemukan',
                'data'    => null
            ], 404);
        }

        Storage::delete('public/transports/' . $transport->photo);

        $transport->delete();

        return response()->json([
            'success' => true,
            'message' => 'Data Transport berhasil dihapus',
            'data'    => $transport
        ], 200);
    }
}

resources/views/transports/index.blade.php
@extends('layouts.app')

@section('title', 'List Transport')

@push('style')
    <!-- CSS Libraries -->
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Transport</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-transport active"><a href="#">List Transport</a></div>
                    <div class="breadcrumb-transport"><a href="#"></a></div>
                </div>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Tabel Transport</h4>
                                <div class="card-header-action d-flex">
                                    <form action="{{ route('transports.index') }}" method="GET">
                                        <div class="input-group pr-2">
                                            <input type="text" class="form-control" name="search" placeholder="Search"
                                                value="{{ request()->query('search') }}">
                                            <div class="input-group-btn">
                                                <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                            </div>
                                        </div>
                                    </form>
                                    <a href="{{ route('transports.create') }}">
                                        <button class="btn btn-primary">
                                            Add Transport
                                        </button>
                                    </a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table-bordered table-md table">
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Photo</th>
                                            <th>Number Phone</th>
                                            <th>Address</th>
                                            <th>Price</th>
                                            <th>Time</th>
                                            <th>Capacity</th>
                                            <th>City</th>
                                            <th>Owner</th>
                                            <th>Type</th>
                                            <th>Description</th>
                                            <th class="text-center">Action</th>
                                        </tr>

                                        @if ($transports->isEmpty())
                                            <tr>
                                                <td colspan="8" class="text-center">No data available</td>
                                            </tr>
                                        @endif
                                        @foreach ($transports as $transport)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $transport->name }}</td>
                                                <td><img width="100" height="100"
                                                        src="{{ asset("storage/transports/$transport->photo") }}"
                                                        alt="">
                                                </td>
                                                <td>{{ $transport->number_phone }}</td>
                                                <td>{{ $transport->address }}</td>
                                                <td>{{ $transport->price }}</td>
                                                <td>{{ $transport->time }}</td>
                                                <td>{{ $transport->capacity }}</td>
                                                <td>{{ $transport->city }}</td>
                                                <td>{{ $transport->owner }}</td>
                                                <td>{{ $transport->type }}</td>
                                                <td>{{ $transport->description }}</td>
                                                <td>
                                                    <a href="{{ route('transports.edit', ['transport' => $transport]) }}"
                                                        class="btn btn-warning btn-sm">Edit</a>
                                                    <form action="{{ route('transports.destroy', $transport->id) }}"
                                                        method="POST" class="d-inline">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer text-right">
                                <nav class="d-inline-block">
                                    {{ $transports->links() }}
                                </nav>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->

    <!-- Page Specific JS File -->
@endpush