routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\CampusController;
use App\Http\Controllers\CulinaryController;
use App\Http\Controllers\DormController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SummaryController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TransportController;
use App\Http\Controllers\WritingController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
Route::group([], function () {
    Route::resource('books', BookController::class);
    Route::resource('campuses', CampusController::class);
    Route::resource('organizations', OrganizationController::class);
    Route::resource('transports', TransportController::class);
    Route::resource('culinaries', CulinaryController::class);
    Route::resource('dorms', DormController::class);
    Route::resource('news', NewsController::class);
    Route::get('news/publish/{id}', [NewsController::class, 'publish'])->name('news.publish');
    Route::get('news/unpublish/{id}', [NewsController::class, 'unpublish'])->name('news.unpublish');

    Route::resource('summaries', SummaryController::class);
    // summary publish and unpublish
    Route::get('summaries/publish/{id}', [SummaryController::class, 'publish'])->name('summaries.publish');
    Route::get('summaries/unpublish/{id}', [SummaryController::class, 'unpublish'])->name('summaries.unpublish');

    Route::resource('writings', WritingController::class);
    // writings publish and unpublish
    Route::get('writings/publish/{id}', [WritingController::class, 'publish'])->name('writings.publish');
    Route::get('writings/unpublish/{id}', [WritingController::class, 'unpublish'])->name('writings.unpublish');

    Route::resource('students', StudentController::class);
    Route::resource('teachers', TeacherController::class);

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');


    // Dashboard
    Route::get('/dashboard-ecommerce-dashboard', function () {
        return view('pages.dashboard-ecommerce-dashboard', ['type_menu' => 'dashboard']);
    });


    // Layout
    Route::get('/layout-default-layout', function () {
        return view('pages.layout-default-layout', ['type_menu' => 'layout']);
    });

    // Blank Page
    Route::get('/blank-page', function () {
        return view('pages.blank-page', ['type_menu' => '']);
    });

    // Bootstrap
    Route::get('/bootstrap-alert', function () {
        return view('pages.bootstrap-alert', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-badge', function () {
        return view('pages.bootstrap-badge', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-breadcrumb', function () {
        return view('pages.bootstrap-breadcrumb', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-buttons', function () {
        return view('pages.bootstrap-buttons', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-card', function () {
        return view('pages.bootstrap-card', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-carousel', function () {
        return view('pages.bootstrap-carousel', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-collapse', function () {
        return view('pages.bootstrap-collapse', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-dropdown', function () {
        return view('pages.bootstrap-dropdown', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-form', function () {
        return view('pages.bootstrap-form', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-list-group', function () {
        return view('pages.bootstrap-list-group', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-media-object', function () {
        return view('pages.bootstrap-media-object', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-modal', function () {
        return view('pages.bootstrap-modal', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-nav', function () {
        return view('pages.bootstrap-nav', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-navbar', function () {
        return view('pages.bootstrap-navbar', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-pagination', function () {
        return view('pages.bootstrap-pagination', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-popover', function () {
        return view('pages.bootstrap-popover', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-progress', function () {
        return view('pages.bootstrap-progress', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-table', function () {
        return view('pages.bootstrap-table', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-tooltip', function () {
        return view('pages.bootstrap-tooltip', ['type_menu' => 'bootstrap']);
    });
    Route::get('/bootstrap-typography', function () {
        return view('pages.bootstrap-typography', ['type_menu' => 'bootstrap']);
    });


    // components
    Route::get('/components-article', function () {
        return view('pages.components-article', ['type_menu' => 'components']);
    });
    Route::get('/components-avatar', function () {
        return view('pages.components-avatar', ['type_menu' => 'components']);
    });
    Route::get('/components-chat-box', function () {
        return view('pages.components-chat-box', ['type_menu' => 'components']);
    });
    Route::get('/components-empty-state', function () {
        return view('pages.components-empty-state', ['type_menu' => 'components']);
    });
    Route::get('/components-gallery', function () {
        return view('pages.components-gallery', ['type_menu' => 'components']);
    });
    Route::get('/components-hero', function () {
        return view('pages.components-hero', ['type_menu' => 'components']);
    });
    Route::get('/components-multiple-upload', function () {
        return view('pages.components-multiple-upload', ['type_menu' => 'components']);
    });
    Route::get('/components-pricing', function () {
        return view('pages.components-pricing', ['type_menu' => 'components']);
    });
    Route::get('/components-statistic', function () {
        return view('pages.components-statistic', ['type_menu' => 'components']);
    });
    Route::get('/components-tab', function () {
        return view('pages.components-tab', ['type_menu' => 'components']);
    });
    Route::get('/components-table', function () {
        return view('pages.components-table', ['type_menu' => 'components']);
    });
    Route::get('/components-user', function () {
        return view('pages.components-user', ['type_menu' => 'components']);
    });
    Route::get('/components-wizard', function () {
        return view('pages.components-wizard', ['type_menu' => 'components']);
    });

    // forms
    Route::get('/forms-advanced-form', function () {
        return view('pages.forms-advanced-form', ['type_menu' => 'forms']);
    });
    Route::get('/forms-editor', function () {
        return view('pages.forms-editor', ['type_menu' => 'forms']);
    });
    Route::get('/forms-validation', function () {
        return view('pages.forms-validation', ['type_menu' => 'forms']);
    });

    // google maps
    // belum tersedia

    // modules
    Route::get('/modules-calendar', function () {
        return view('pages.modules-calendar', ['type_menu' => 'modules']);
    });
    Route::get('/modules-chartjs', function () {
        return view('pages.modules-chartjs', ['type_menu' => 'modules']);
    });
    Route::get('/modules-datatables', function () {
        return view('pages.modules-datatables', ['type_menu' => 'modules']);
    });
    Route::get('/modules-flag', function () {
        return view('pages.modules-flag', ['type_menu' => 'modules']);
    });
    Route::get('/modules-font-awesome', function () {
        return view('pages.modules-font-awesome', ['type_menu' => 'modules']);
    });
    Route::get('/modules-ion-icons', function () {
        return view('pages.modules-ion-icons', ['type_menu' => 'modules']);
    });
    Route::get('/modules-owl-carousel', function () {
        return view('pages.modules-owl-carousel', ['type_menu' => 'modules']);
    });
    Route::get('/modules-sparkline', function () {
        return view('pages.modules-sparkline', ['type_menu' => 'modules']);
    });
    Route::get('/modules-sweet-alert', function () {
        return view('pages.modules-sweet-alert', ['type_menu' => 'modules']);
    });
    Route::get('/modules-toastr', function () {
        return view('pages.modules-toastr', ['type_menu' => 'modules']);
    });
    Route::get('/modules-vector-map', function () {
        return view('pages.modules-vector-map', ['type_menu' => 'modules']);
    });
    Route::get('/modules-weather-icon', function () {
        return view('pages.modules-weather-icon', ['type_menu' => 'modules']);
    });

    // auth
    Route::get('/auth-forgot-password', function () {

app/Models/Organization.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Organization extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'address',
        'number_phone',
        'photo',
        'email',
        'description',
        'instagram',
    ];
}

app/Http/Controllers/API/V1/OrganizationController.php
<?php

namespace App\Http\Controllers\API\V1;

use App\Http\Controllers\Controller;
use App\Models\Organization;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class OrganizationController extends Controller
{
    //    protected $fillable = [
    //     'name',
    //     'address',
    //     'number_phone',
    //     'photo',
    //     'email',
    //     'description',
    //     'instagram',
    // ];

    public function index()
    {
        $organizations = Organization::latest()->get();
        $organizations->map(function ($organization) {
            $organization->photo = env('APP_URL') . Storage::url('organizations/' . $organization->photo);
            return $organization;
        });
        return response()->json([
            'success' => true,
            'message' => 'List Data Organization',
            'data'    => $organizations
        ], 200);
    }

    public function show($id)
    {
        $organization = Organization::find($id);

        $organization->photo = env('APP_URL') . Storage::url('organizations/' . $organization->photo);

        if (!$organization) {
            return response()->json([
                'success' => false,
                'message' => 'Organization tidak ditemukan',
                'data'    => null
            ], 404);
        }

        return response()->json([
            'success' => true,
            'message' => 'Detail Data Organization',
            'data'    => $organization
        ], 200);
    }

    public function store(Request $request)
    {
        $validateData = $request->validate([
            'name' => 'required|max:255',
            'address' => 'required|max:255',
            'number_phone' => 'required|max:255',
            'photo' => 'file|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'email' => 'required|max:255',
            'description' => 'required|max:255',
            'instagram' => 'required|max:255',
        ]);

        $organization = new Organization();

        $organization->fill($validateData);

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $filename = time() . '.' . $photo->getClientOriginalExtension();
            Storage::putFileAs('public/organizations', $photo, $filename);
            $organization->photo = $filename;
        }

        $organization->save();

        return response()->json([
            'success' => true,
            'message' => 'Organization berhasil ditambahkan',
            'data'    => $organization
        ], 200);
    }

    public function update(Request $request, $id)
    {
        $organization = Organization::find($id);

        if (!$organization) {
            return response()->json([
                'success' => false,
                'message' => 'Organization tidak ditemukan',
                'data'    => null
            ], 404);
        }

        $validateData = $request->validate([
            'name' => 'required|max:255',
            'address' => 'required|max:255',
            'number_phone' => 'required|max:255',
            'photo' => 'file|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'email' => 'required|max:255',
            'description' => 'required|max:255',
            'instagram' => 'required|max:255',
        ]);

        $organization->fill($validateData);

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $filename = time() . '.' . $photo->getClientOriginalExtension();
            Storage::putFileAs('public/organizations', $photo, $filename);
            Storage::delete('public/organizations/' . $organization->photo);
            $organization->photo = $filename;
        }

        $organization->save();

        return response()->json([
            'success' => true,
            'message' => 'Organization berhasil diupdate',
            'data'    => $organization
        ], 200);
    }

    public function destroy($id)
    {
        $organization = Organization::find($id);

        if (!$organization) {
            return response()->json([
                'success' => false,
                'message' => 'Organization tidak ditemukan',
                'data'    => null
            ], 404);
        }

        $organization->delete();

        return response()->json([
            'success' => true,
            'message' => 'Organization berhasil dihapus',
            'data'    => $organization
        ], 200);
    }
}

resources/views/organizations/create.blade.php
@extends('layouts.app')

@section('name', 'Create Organization')

@push('style')
    <!-- CSS Libraries -->
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Organization</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Organization</a></div>
                    <div class="breadcrumb-item"><a href="#">Create</a></div>
                </div>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="card">
                            <form action="{{ route('organizations.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="card-header">
                                    <h4>Create Organization</h4>

                                </div>
                                <div class="card-body row">
                                    <div class="col-md-6 col-lg-6">
                                        {{-- form name --}}
                                        <div class="form-group">
                                            <label>Name</label>
                                            <input type="text" class="form-control @error('name') is-invalid @enderror "
                                                name="name" value="{{ old('name') }}" required="">
                                            @error('name')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form address --}}
                                        <div class="form-group">
                                            <label>Address</label>
                                            <input type="text"
                                                class="form-control @error('address') is-invalid @enderror " name="address"
                                                value="{{ old('address') }}" required="">
                                            @error('address')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form number_phone --}}
                                        <div class="form-group">
                                            <label>Number Phone</label>
                                            <input type="text"
                                                class="form-control @error('number_phone') is-invalid @enderror "
                                                name="number_phone" value="{{ old('number_phone') }}" required="">
                                            @error('number_phone')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form email --}}
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="email" class="form-control @error('email') is-invalid @enderror "
                                                name="email" value="{{ old('email') }}" required="">
                                            @error('email')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-lg-6">

                                        {{-- form description --}}
                                        <div class="form-group">
                                            <label>Description</label>
                                            <textarea type="text" class="form-control @error('description') is-invalid @enderror " name="description"
                                                value="" required="" style="height: 100px;">{{ old('description') }}</textarea>
                                            @error('description')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form photo cover --}}
                                        <div class="form-group">
                                            <label>Photo</label>
                                            <input type="file" class="form-control @error('photo') is-invalid @enderror "
                                                name="photo" value="@old('photo'))">
                                            @error('photo')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                        {{-- form instagram --}}
                                        <div class="form-group">
                                            <label>Instagram</label>
                                            <input class="form-control @error('instagram') is-invalid @enderror "
                                                name="instagram" value="{{ @old('instagram') }}" required=""
                                                type="text">
                                            @error('instagram')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>

                                    </div>
                                </div>
                                <div class="card-footer text-right">
                                    <button class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->

    <!-- Page Specific JS File -->
@endpush

resources/views/organizations/index.blade.php
@extends('layouts.app')

@section('title', 'List Organization')

@push('style')
    <!-- CSS Libraries -->
@endpush

@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Organization</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-organization active"><a href="#">Organization</a></div>
                    <div class="breadcrumb-organization"><a href="#">List</a></div>
                </div>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Tabel Organization</h4>
                                <div class="card-header-action d-flex">
                                    <form action="{{ route('organizations.index') }}" method="GET">
                                        <div class="input-group pr-2">
                                            <input type="text" class="form-control" placeholder="Search" name="search"
                                                value="{{ request()->query('search') }}">
                                            <div class="input-group-btn">
                                                <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                            </div>
                                        </div>
                                    </form>
                                    <a href="{{ route('organizations.create') }}">
                                        <button class="btn btn-primary">
                                            Add Organization
                                        </button>
                                    </a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table-bordered table-md table">
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Photo</th>
                                            <th>Number Phone</th>
                                            <th>Address</th>
                                            <th>Instagram</th>
                                            <th>Description</th>
                                            <th class="text-center">Action</th>
                                        </tr>

                                        @if ($organizations->isEmpty())
                                            <tr>
                                                <td colspan="8" class="text-center">No data available</td>
                                            </tr>
                                        @endif
                                        @foreach ($organizations as $organization)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $organization->name }}</td>
                                                <td>{{ $organization->email }}</td>
                                                <td><img width="100" height="100"
                                                        src="{{ asset("storage/organizations/$organization->photo") }}"
                                                        alt="">
                                                </td>
                                                <td>{{ $organization->number_phone }}</td>
                                                <td>{{ $organization->address }}</td>
                                                <td>{{ $organization->instagram }}</td>
                                                <td>{{ $organization->description }}</td>
                                                <td>
                                                    <a href="{{ route('organizations.edit', ['organization' => $organization]) }}"
                                                        class="btn btn-warning btn-sm">Edit</a>
                                                    <form action="{{ route('organizations.destroy', $organization->id) }}"
                                                        method="POST" class="d-inline">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer text-right">
                                <nav class="d-inline-block">
                                    <ul class="pagination mb-0">
                                        <li class="page-organization disabled">
                                            <a class="page-link" href="#" tabindex="-1"><i
                                                    class="fas fa-chevron-left"></i></a>
                                        </li>
                                        <li class="page-organization active"><a class="page-link" href="#">1 <span
                                                    class="sr-only">(current)</span></a></li>
                                        <li class="page-organization">
                                            <a class="page-link" href="#">2</a>
                                        </li>
                                        <li class="page-organization"><a class="page-link" href="#">3</a></li>
                                        <li class="page-organization">
                                            <a class="page-link" href="#"><i class="fas fa-chevron-right"></i></a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->

    <!-- Page Specific JS File -->
@endpush